name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Stage 1
      id: stage1
      continue-on-error: true
      run: ./britishinput fail
    - name: Stage 2
      id: stage2
      if: steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput fail
    - name: Stage 3
      id: stage3
      if: steps.stage2.outcome == 'failure' && steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput fail
    - name: Stage 4
      id: stage4
      if: steps.stage3.outcome == 'failure' && steps.stage2.outcome == 'failure' && steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput fail
    - name: Stage 5
      id: stage5
      if: steps.stage4.outcome == 'failure' && steps.stage3.outcome == 'failure' && steps.stage2.outcome == 'failure' && steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput pass
    - name: Stage 6
      id: stage6
      if: steps.stage5.outcome == 'failure' && steps.stage4.outcome == 'failure' && steps.stage3.outcome == 'failure' && steps.stage2.outcome == 'failure' && steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput
    - name: Stage 7
      id: stage7
      if: steps.stage6.outcome == 'failure' && steps.stage5.outcome == 'failure' && steps.stage4.outcome == 'failure' && steps.stage3.outcome == 'failure' && steps.stage2.outcome == 'failure' && steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput
    - name: Stage 8
      id: stage8
      if: steps.stage7.outcome == 'failure' && steps.stage6.outcome == 'failure' && steps.stage5.outcome == 'failure' && steps.stage4.outcome == 'failure' && steps.stage3.outcome == 'failure' && steps.stage2.outcome == 'failure' && steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput
    - name: Stage 9
      id: stage9
      if: steps.stage8.outcome == 'failure' && steps.stage7.outcome == 'failure' && steps.stage6.outcome == 'failure' && steps.stage5.outcome == 'failure' && steps.stage4.outcome == 'failure' && steps.stage3.outcome == 'failure' && steps.stage2.outcome == 'failure' && steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput
    - name: Stage 10
      id: stage10
      if: steps.stage9.outcome == 'failure' && steps.stage8.outcome == 'failure' && steps.stage7.outcome == 'failure' && steps.stage6.outcome == 'failure' && steps.stage5.outcome == 'failure' && steps.stage4.outcome == 'failure' && steps.stage3.outcome == 'failure' && steps.stage2.outcome == 'failure' && steps.stage1.outcome == 'failure'
      continue-on-error: true
      run: ./britishinput
    - name: Final Status
      if: always()
      run: |-
        if [[ "${{ steps.stage1.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage2.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage3.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage4.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage5.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage6.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage7.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage8.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage9.outcome }}" == 'success' ]] || \
           [[ "${{ steps.stage10.outcome }}" == 'success' ]]; then
          echo "Pipeline succeeded - a stage passed"
          exit 0
        else
          echo "Pipeline failed - no stage passed"
          exit 1
        fi
