name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Stage 1
      id: stage1
      continue-on-error: true
      run: |
        ./britishinput fail
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 2
      id: stage2
      if: steps.stage1.outputs.success != 'true'
      continue-on-error: true
      run: |
        ./britishinput fail
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 3
      id: stage3
      if: steps.stage2.outputs.success != 'true'
      continue-on-error: true
      run: |
        ./britishinput fail
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 4
      id: stage4
      if: steps.stage3.outputs.success != 'true'
      continue-on-error: true
      run: |
        ./britishinput fail
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 5
      id: stage5
      if: steps.stage4.outputs.success != 'true'
      continue-on-error: true
      run: |
        ./britishinput pass
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 6
      id: stage6
      if: steps.stage5.outputs.success != 'true'
      continue-on-error: true
      run: |
        ./britishinput
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 7
      id: stage7
      if: steps.stage6.outputs.success != 'true'
      continue-on-error: true
      run: |
        ./britishinput
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 8
      id: stage8
      if: steps.stage7.outputs.success != 'true'
      continue-on-error: true
      run: |
        ./britishinput
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 9
      id: stage9
      if: steps.stage8.outputs.success != 'true'
      continue-on-error: true
      run: |
        ./britishinput
        echo "success=true" >> $GITHUB_OUTPUT
    - name: Stage 10
      if: steps.stage9.outputs.success != 'true'
      run: |
        ./britishinput
