name: Build & Test
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: 01 13 * * SAT
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3b9b8c884f6b4bb4d5be2779c26374abadae0871
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: stable
      - run: go build
      - run: ./britishinput pass
  stage2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3b9b8c884f6b4bb4d5be2779c26374abadae0871
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: stable
      - run: go build
      - run: ./britishinput pass
  pipeline-status:
    name: Pipeline Status
    needs:
      - stage1
      - stage2
    if: always()
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: All Tests Passed
        run: |-
          if [[ "${{ needs.stage1.result }}" == "success" ]] || [[ "${{ needs.stage2.result }}" == "success" ]]; then
            echo "At least one stage succeeded"
            exit 0
          else
            echo "No stages succeeded"
            exit 1
          fi
