name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Stage 1
      id: stage1
      run: |
        if ./britishinput fail; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 2
      id: stage2
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput fail; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 3
      id: stage3
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput fail; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 4
      id: stage4
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput fail; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 5
      id: stage5
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput pass; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 6
      id: stage6
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 7
      id: stage7
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 8
      id: stage8
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 9
      id: stage9
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 10
      id: stage10
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Final Status
      if: always()
      run: |
        if [[ "${{ env.STAGE_SUCCEEDED }}" == 'true' ]]; then
          echo "Pipeline succeeded - a stage passed"
          exit 0
        else
          echo "Pipeline failed - no stage passed"
          exit 1
        fi
