name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Stage 1
      run: |
        if ! ./britishinput fail; then
          echo "Stage 1 failed, continuing to Stage 2"
          exit 1
        fi
    - name: Stage 2
      if: failure()
      run: |
        if ! ./britishinput fail; then
          echo "Stage 2 failed, continuing to Stage 3"
          exit 1
        fi
    - name: Stage 3
      if: failure()
      run: |
        if ! ./britishinput fail; then
          echo "Stage 3 failed, continuing to Stage 4"
          exit 1
        fi
    - name: Stage 4
      if: failure()
      run: |
        if ! ./britishinput fail; then
          echo "Stage 4 failed, continuing to Stage 5"
          exit 1
        fi
    - name: Stage 5
      if: failure()
      run: |
        ./britishinput pass
    - name: Stage 6
      if: failure()
      run: |
        if ! ./britishinput; then
          echo "Stage 6 failed, continuing to Stage 7"
          exit 1
        fi
    - name: Stage 7
      if: failure()
      run: |
        if ! ./britishinput; then
          echo "Stage 7 failed, continuing to Stage 8"
          exit 1
        fi
    - name: Stage 8
      if: failure()
      run: |
        if ! ./britishinput; then
          echo "Stage 8 failed, continuing to Stage 9"
          exit 1
        fi
    - name: Stage 9
      if: failure()
      run: |
        if ! ./britishinput; then
          echo "Stage 9 failed, continuing to Stage 10"
          exit 1
        fi
    - name: Stage 10
      if: failure()
      run: ./britishinput
