name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Stage 1
      id: stage1
      run: |
        ./britishinput fail
    - name: Stage 2
      id: stage2
      if: failure()
      run: |
        ./britishinput fail
    - name: Stage 3
      id: stage3
      if: failure()
      run: |
        ./britishinput fail
    - name: Stage 4
      id: stage4
      if: failure()
      run: |
        ./britishinput fail
    - name: Stage 5
      id: stage5
      if: failure()
      run: |
        ./britishinput pass
    - name: Stage 6
      id: stage6
      if: failure()
      run: |
        ./britishinput
    - name: Stage 7
      id: stage7
      if: failure()
      run: |
        ./britishinput
    - name: Stage 8
      id: stage8
      if: failure()
      run: |
        ./britishinput
    - name: Stage 9
      id: stage9
      if: failure()
      run: |
        ./britishinput
    - name: Stage 10
      id: stage10
      if: failure()
      run: |
        ./britishinput
