name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Run Stages
      id: run_stages
      run: |
        for i in {1..4}; do
          echo "::group::Stage $i"
          ./britishinput fail || continue
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
          echo "::endgroup::"
        done

        echo "::group::Stage 5"
        if ./britishinput pass; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        echo "::endgroup::"

        for i in {6..10}; do
          echo "::group::Stage $i"
          ./britishinput || continue
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
          echo "::endgroup::"
        done

        exit 1
    - name: Final Status
      if: always()
      run: |
        if [[ "${{ env.STAGE_SUCCEEDED }}" == 'true' ]]; then
          echo "Pipeline succeeded - a stage passed"
          exit 0
        else
          echo "Pipeline failed - no stage passed"
          exit 1
        fi
