name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Stage 1
      id: stage1
      run: |
        ./britishinput fail || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE1_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 2
      id: stage2
      if: env.STAGE1_FAILED == 'true'
      run: |
        ./britishinput fail || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE2_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 3
      id: stage3
      if: env.STAGE1_FAILED == 'true' && env.STAGE2_FAILED == 'true'
      run: |
        ./britishinput fail || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE3_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 4
      id: stage4
      if: env.STAGE1_FAILED == 'true' && env.STAGE2_FAILED == 'true' && env.STAGE3_FAILED == 'true'
      run: |
        ./britishinput fail || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE4_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 5
      id: stage5
      if: env.STAGE1_FAILED == 'true' && env.STAGE2_FAILED == 'true' && env.STAGE3_FAILED == 'true' && env.STAGE4_FAILED == 'true'
      run: |
        ./britishinput pass || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE5_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 6
      id: stage6
      if: env.STAGE1_FAILED == 'true' && env.STAGE2_FAILED == 'true' && env.STAGE3_FAILED == 'true' && env.STAGE4_FAILED == 'true' && env.STAGE5_FAILED == 'true'
      run: |
        ./britishinput || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE6_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 7
      id: stage7
      if: env.STAGE1_FAILED == 'true' && env.STAGE2_FAILED == 'true' && env.STAGE3_FAILED == 'true' && env.STAGE4_FAILED == 'true' && env.STAGE5_FAILED == 'true' && env.STAGE6_FAILED == 'true'
      run: |
        ./britishinput || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE7_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 8
      id: stage8
      if: env.STAGE1_FAILED == 'true' && env.STAGE2_FAILED == 'true' && env.STAGE3_FAILED == 'true' && env.STAGE4_FAILED == 'true' && env.STAGE5_FAILED == 'true' && env.STAGE6_FAILED == 'true' && env.STAGE7_FAILED == 'true'
      run: |
        ./britishinput || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE8_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 9
      id: stage9
      if: env.STAGE1_FAILED == 'true' && env.STAGE2_FAILED == 'true' && env.STAGE3_FAILED == 'true' && env.STAGE4_FAILED == 'true' && env.STAGE5_FAILED == 'true' && env.STAGE6_FAILED == 'true' && env.STAGE7_FAILED == 'true' && env.STAGE8_FAILED == 'true'
      run: |
        ./britishinput || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE9_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Stage 10
      id: stage10
      if: env.STAGE1_FAILED == 'true' && env.STAGE2_FAILED == 'true' && env.STAGE3_FAILED == 'true' && env.STAGE4_FAILED == 'true' && env.STAGE5_FAILED == 'true' && env.STAGE6_FAILED == 'true' && env.STAGE7_FAILED == 'true' && env.STAGE8_FAILED == 'true' && env.STAGE9_FAILED == 'true'
      run: |
        ./britishinput || {
          exit_code=$?
          if [ "$exit_code" == "0" ]; then
            exit 0
          else
            echo "STAGE10_FAILED=true" >> $GITHUB_ENV
            exit 1
          fi
        }
    - name: Final Status
      if: always()
      run: |-
        if [[ "${{ env.STAGE1_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE2_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE3_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE4_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE5_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE6_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE7_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE8_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE9_FAILED }}" != 'true' ]] || \
           [[ "${{ env.STAGE10_FAILED }}" != 'true' ]]; then
          echo "Pipeline succeeded - a stage passed"
          exit 0
        else
          echo "Pipeline failed - no stage passed"
          exit 1
        fi
