name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Initialize Status
      run: |
        echo "ANY_SUCCEEDED=false" >> $GITHUB_ENV
    - name: Stage 1
      id: stage1
      continue-on-error: true
      run: |
        output=$(./britishinput fail || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 2
      id: stage2
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput fail || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 3
      id: stage3
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput fail || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 4
      id: stage4
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput fail || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 5
      id: stage5
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput pass || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 6
      id: stage6
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 7
      id: stage7
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 8
      id: stage8
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 9
      id: stage9
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Stage 10
      id: stage10
      if: env.ANY_SUCCEEDED != 'true'
      continue-on-error: true
      run: |
        output=$(./britishinput || echo "FAILED")
        if [[ "$output" != "FAILED" ]]; then
          echo "ANY_SUCCEEDED=true" >> $GITHUB_ENV
          exit 0
        fi
        exit 1
    - name: Final Status
      if: always()
      run: |-
        if [[ "${{ env.ANY_SUCCEEDED }}" == 'true' ]]; then
          echo "Pipeline succeeded - a stage passed"
          exit 0
        else
          echo "Pipeline failed - no stage passed"
          exit 1
        fi
