name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Stage 1
      run: |
        ./britishinput pass
    - name: Stage 2
      if: failure()
      run: |
        ./britishinput pass
    - name: Stage 3
      if: failure()
      run: |
        ./britishinput fail
    - name: Stage 4
      if: failure()
      run: |
        ./britishinput fail
    - name: Stage 5
      if: failure()
      run: |
        ./britishinput
    - name: Stage 6
      if: failure()
      run: |
        ./britishinput
    - name: Stage 7
      if: failure()
      run: |
        ./britishinput
    - name: Stage 8
      if: failure()
      run: |
        ./britishinput
    - name: Stage 9
      if: failure()
      run: |
        ./britishinput
    - name: Stage 10
      if: failure()
      run: |-
        ./britishinput
