name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  pipeline:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      STAGE_SUCCEEDED: "false"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.21'
    - name: Build
      run: go build -v
    - name: Stage 1
      if: env.STAGE_SUCCEEDED != 'true'
      run: |
        ./britishinput fail || echo "Stage 1 failed"
    - name: Stage 2
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        ./britishinput fail || echo "Stage 2 failed"
    - name: Stage 3
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        ./britishinput fail || echo "Stage 3 failed"
    - name: Stage 4
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        ./britishinput fail || echo "Stage 4 failed"
    - name: Stage 5
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput pass; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 6
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 7
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 8
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 9
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
    - name: Stage 10
      if: failure() && env.STAGE_SUCCEEDED != 'true'
      run: |
        if ./britishinput; then
          echo "STAGE_SUCCEEDED=true" >> $GITHUB_ENV
        fi
