name: Build & Test
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: 01 13 * * SAT
jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ">=1.21"
      - run: go build -v
      - run: ./britishinput pass
  stage2:
    needs: stage1
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version: ">=1.21"
      - run: go build -v
      - run: ./britishinput pass
  final-status:
    name: All Tests Passed
    needs:
      - stage1
      - stage2
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |-
          if [[ "${{ needs.stage1.result }}" == "success" ]] || \
             [[ "${{ needs.stage2.result }}" == "success" ]]; then \
            echo "Pipeline succeeded - a stage passed"
            exit 0
          fi

          echo "Pipeline failed - no stage passed"
          exit 1
